name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t tiny-nextflow-example .

      - name: Run pytest in Docker
        run: docker run --rm tiny-nextflow-example pytest -q tests/

      - name: Run Nextflow workflow in Docker
        run: docker run --rm tiny-nextflow-example nextflow run main.nf -profile docker -with-dag dag.png